# Import libray tensforflow

In [3]:
import tensorflow as tf

## Buatlah sebuah tensor dengan shape(5,5) dengan nilai random yang disimpan dalam variable random_tensor

In [6]:
random_tensor = tf.random.normal([5,5])
random_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 0.7695022 , -0.7580773 ,  2.4435413 ,  0.2593875 ,  0.33514294],
       [ 1.2734538 ,  0.8510116 ,  1.4060466 ,  0.584049  , -0.48842156],
       [ 0.2638065 ,  0.717292  ,  2.1402295 , -1.8738679 ,  0.32165954],
       [-0.5954158 ,  0.5621245 ,  0.24011481,  1.5529006 , -0.6044808 ],
       [-0.89263195, -1.304264  ,  1.1460057 ,  1.7472647 ,  0.33028686]],
      dtype=float32)>

## Buatlah sebuah tensor dengan shape(5,5) dari sebuah list dengan nilai bilangan prima dalam variable prime_tensor

In [8]:
list = [[4, 8, 9, 12, 13],
       [14, 15, 16, 19, 21],
       [34, 35, 38, 40, 42],
       [ 49, 54, 55, 56, 71],
       [ 76, 79, 85, 86, 88]]
prime_tensor = tf.convert_to_tensor(list, dtype=tf.float32)
prime_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 4.,  8.,  9., 12., 13.],
       [14., 15., 16., 19., 21.],
       [34., 35., 38., 40., 42.],
       [49., 54., 55., 56., 71.],
       [76., 79., 85., 86., 88.]], dtype=float32)>

## Tampilkan dimensi dari kedua variable tersebut

In [10]:
print ("Dimensi variabel random tensor : ", random_tensor.shape)
print ("Dimensi variabel random tensor : ", prime_tensor.shape)

Dimensi variabel random tensor :  (5, 5)
Dimensi variabel random tensor :  (5, 5)


## Tampilkan hasil dari perhitungan aritmetika 2 variable tersebut (Gunakan minimal 5 operator)

## Perjumlahan

In [11]:
tf.add(random_tensor,prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 4.769502,  7.241923, 11.443542, 12.259388, 13.335143],
       [15.273454, 15.851011, 17.406046, 19.58405 , 20.511578],
       [34.263805, 35.717293, 40.14023 , 38.126133, 42.32166 ],
       [48.404583, 54.562126, 55.240116, 57.552902, 70.395515],
       [75.10737 , 77.69574 , 86.146   , 87.74726 , 88.330284]],
      dtype=float32)>

## pengurangan

In [14]:
tf.subtract(random_tensor,prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ -3.2304978,  -8.758078 ,  -6.5564585, -11.740612 , -12.664857 ],
       [-12.726546 , -14.148989 , -14.593953 , -18.41595  , -21.488422 ],
       [-33.736195 , -34.282707 , -35.85977  , -41.873867 , -41.67834  ],
       [-49.595417 , -53.437874 , -54.759884 , -54.447098 , -71.604485 ],
       [-76.89263  , -80.30426  , -83.854    , -84.25274  , -87.669716 ]],
      dtype=float32)>

## Perkalian

In [15]:
tf.multiply(random_tensor,prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[   3.078009 ,   -6.0646186,   21.99187  ,    3.11265  ,
           4.3568583],
       [  17.828354 ,   12.765174 ,   22.496746 ,   11.0969305,
         -10.256853 ],
       [   8.96942  ,   25.10522  ,   81.32872  ,  -74.95471  ,
          13.509701 ],
       [ -29.175373 ,   30.354723 ,   13.206314 ,   86.96243  ,
         -42.918137 ],
       [ -67.84003  , -103.03685  ,   97.41049  ,  150.26477  ,
          29.065243 ]], dtype=float32)>

## Pembagian

In [16]:
tf.divide(random_tensor,prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 0.19237556, -0.09475967,  0.27150458,  0.02161562,  0.02578023],
       [ 0.09096099,  0.0567341 ,  0.08787791,  0.03073942, -0.02325817],
       [ 0.00775901,  0.02049406,  0.05632183, -0.0468467 ,  0.00765856],
       [-0.01215134,  0.01040971,  0.00436572,  0.02773037, -0.00851381],
       [-0.01174516, -0.01650967,  0.01348242,  0.02031703,  0.00375326]],
      dtype=float32)>

## Pangkat

In [17]:
tf.pow(random_tensor,prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 3.5062230e-01,  1.0907069e-01,  3.1058262e+03,  9.2765902e-08,
         6.7296270e-07],
       [ 2.9496119e+01,  8.8926665e-02,  2.3334343e+02,  3.6520458e-05,
        -2.9153543e-07],
       [ 2.1072025e-20,  8.8993802e-06,  3.6098807e+12,  8.1200480e+10,
         2.0447963e-21],
       [-9.2511632e-12,  3.0971011e-14,  8.3761015e-35,  5.0587603e+10,
        -3.0071732e-16],
       [ 1.7828074e-04, -1.2997916e+09,  1.0736870e+05,  6.9638493e+20,
         0.0000000e+00]], dtype=float32)>

## Tampilkan nilai maksimal dan minimal dari variable random_tensor

In [19]:
print("Nilai maksima dari variabel random tensor: ", tf.argmax(random_tensor))

Nilai maksima dari variabel random tensor:  tf.Tensor([1 1 0 4 0], shape=(5,), dtype=int64)


In [22]:
print("Nilai minimal dari variabel random tensor: ", tf.argmin(random_tensor))

Nilai minimal dari variabel random tensor:  tf.Tensor([4 4 3 2 3], shape=(5,), dtype=int64)


## Tampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)

In [24]:
print("Penggabungan berdasarkan Kolom")
concatenation_col = tf.concat([random_tensor,prime_tensor],axis=0)
concatenation_col

Penggabungan berdasarkan Kolom


<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[ 0.7695022 , -0.7580773 ,  2.4435413 ,  0.2593875 ,  0.33514294],
       [ 1.2734538 ,  0.8510116 ,  1.4060466 ,  0.584049  , -0.48842156],
       [ 0.2638065 ,  0.717292  ,  2.1402295 , -1.8738679 ,  0.32165954],
       [-0.5954158 ,  0.5621245 ,  0.24011481,  1.5529006 , -0.6044808 ],
       [-0.89263195, -1.304264  ,  1.1460057 ,  1.7472647 ,  0.33028686],
       [ 4.        ,  8.        ,  9.        , 12.        , 13.        ],
       [14.        , 15.        , 16.        , 19.        , 21.        ],
       [34.        , 35.        , 38.        , 40.        , 42.        ],
       [49.        , 54.        , 55.        , 56.        , 71.        ],
       [76.        , 79.        , 85.        , 86.        , 88.        ]],
      dtype=float32)>

In [25]:
print("Penggabungan berdasarkan baris")
concatenation_row = tf.concat([random_tensor,prime_tensor],axis=1)
concatenation_row

Penggabungan berdasarkan baris


<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[ 0.7695022 , -0.7580773 ,  2.4435413 ,  0.2593875 ,  0.33514294,
         4.        ,  8.        ,  9.        , 12.        , 13.        ],
       [ 1.2734538 ,  0.8510116 ,  1.4060466 ,  0.584049  , -0.48842156,
        14.        , 15.        , 16.        , 19.        , 21.        ],
       [ 0.2638065 ,  0.717292  ,  2.1402295 , -1.8738679 ,  0.32165954,
        34.        , 35.        , 38.        , 40.        , 42.        ],
       [-0.5954158 ,  0.5621245 ,  0.24011481,  1.5529006 , -0.6044808 ,
        49.        , 54.        , 55.        , 56.        , 71.        ],
       [-0.89263195, -1.304264  ,  1.1460057 ,  1.7472647 ,  0.33028686,
        76.        , 79.        , 85.        , 86.        , 88.        ]],
      dtype=float32)>

## Tampilkan hasil sorting dari kedua variable di atas. (descending)

In [26]:
print("Hasil random tensor secara descending")
print(tf.sort(random_tensor,direction="DESCENDING"))
print("")
print("Hasil prime tensor secara descending")
print(tf.sort(prime_tensor,direction="DESCENDING"))

Hasil random tensor secara descending
tf.Tensor(
[[ 2.4435413   0.7695022   0.33514294  0.2593875  -0.7580773 ]
 [ 1.4060466   1.2734538   0.8510116   0.584049   -0.48842156]
 [ 2.1402295   0.717292    0.32165954  0.2638065  -1.8738679 ]
 [ 1.5529006   0.5621245   0.24011481 -0.5954158  -0.6044808 ]
 [ 1.7472647   1.1460057   0.33028686 -0.89263195 -1.304264  ]], shape=(5, 5), dtype=float32)

Hasil prime tensor secara descending
tf.Tensor(
[[13. 12.  9.  8.  4.]
 [21. 19. 16. 15. 14.]
 [42. 40. 38. 35. 34.]
 [71. 56. 55. 54. 49.]
 [88. 86. 85. 79. 76.]], shape=(5, 5), dtype=float32)
